language: python
python:
- '3.9'
services:
- mysql
before_install:
- sudo mysql -u root --password="" < travis.sql
install:
- pip install -r requirements.txt
env:
  matrix:
  - Channel_ID=827598982020071487 Target_ID=827137883357708288
  global:
  - secure: qSkfK616D9hivwi2fXJRcKhdi6DPz/ejAyXwehN8eJcl3fcv0MPloYavN4AwNOBlZkNdVRAno0uVfAdYReI6bfQJVyLbRifFytuuCuM9ZUXY/nanNEi5Xw4xtsuoCmnRKtdO2nEdCosoI8ck8ZxOBs7HsEIb9blbz41A/+U8vPySP591z82pm1UVNO4nffHepWfOHsFF/rJ3JkgI1Fh6H8N7X6ZYJvG1HWQO7u39dNvfJYDq+kyS9m4tRHOwvW0qteID9S9Uc6auc04c68sDHO7uky6+jbFOusMlL4zdryafVr2Jq3FXCN7szh7YSk3WEqNc2NZBDj8PDwmakkvZAe1fJrZSVd3np0+G41M0CXKKrpZHzeYWyNNa3lUezQ7AjMZcvIjXJdOsFlWtS3aMHl3y9w1EsjaWp+XZTOw8mDy2WhCO+eLdOIjaazqyPXksaMpvE4nAs6GPtfQGFsX6o63ZDbOOUSB4YC/h08g+bHtgAUKiQ0ELJ9r6ytwd/K6ULcgQUpssB3a9xXz961rOD8jni8Ev/jVmZ1WJRbMTl7yD2j2ESz4AcIGzIpTcAxAVn/MbBcl3R3gKUt8sl3xCYVUW0JGfGvpIaJF8IU87AHAs4t2FpiIec4iuCSdRH1eag3esVXXLuzudJv0tIeOKeW1HYXxsAcUNnPvTAvjyXmM=
  - secure: rz4XHescx6Uo/v/brr5UAtvXl1BALFmQcdgGKQSOeuyM/6BCLZ255NPmh9skP1oxFg/P9nNM7ITNCa+bBDhl2yXcycEJjdV087eA9gwbLphfxEKPrEcN9xSC2T8i0TTJtGttf4o8lSgxlPOU7s+z4J12Rhcfy22Zezl7fTbKa32vX9jhm/57Qpei+6naYRRetEqqMSEM3NqGUPLKaGPAcHJTaKNzEiBs/ShJKTqiyNVLFevrEl745pNHK+mRS8fRQ+JYW5R/M+FbhFY23vt26AxjiPIWqkvNm2XiPn6ndaB5nztSzcOHEzc57va70F5fT6IYg/dJGayFuSp0wnNO3QPtojvC3TZNJoZkPJEA8QZ8/5qRj0nNoyjW0Vd89OOKT+Q/AJ1caIPBb18hBf93mOqLEHKEf2HjHqLxmnrmqjgHtJPgJAlzkn2Xu6GsSbtmzcRnaVQiABs7AO54e1jbGfq6+eLGt0nAOY4r3ylVwhiOwjBLbLm0Ke7dPbumpzHI//v1ad8tEpVRncSOxgNTi7W5ISJU6G5zYqUFxONUJwMHq96K1DFB9uqSqewG9COsapdvHRBBPxKa6xGciLdz/vz3tApvz0YN5TqiKoz1lGE6Xkq+YoagH6ipsabDiABYlQPXxYEKX+CBOMNbyLOC/+5uNIZVtrWhdnCRg4S5AhE=
script:
- bash run_test.sh
after_success:
- coveralls
